---
title: "predictor"
author: "mleukam"
date: "2019-07-22"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

The purpose of this notebook is to make a cluster classifier for the HCPC 4-cluster model that can be applied to tumors at UChicago.

## Setup

Clear the workspace
```{r}
rm(list = ls())
```

Load packages
```{r}
library("tidyverse")
library("caret")
library("e1071")
library("Biobase")
```

Read in and format data

https://topepo.github.io/caret/data-splitting.html

```{r}
combined_es <- readRDS("output/combined_es_gsva4_4cluster.rds")

clust <- pData(combined_es) %>%
  rownames_to_column(var = "sample_id") %>%
  dplyr::select(sample_id, clust) %>%
  as_tibble() %>%
  print()

expr_df <- t(exprs(combined_es)) %>%
  as.data.frame() %>%
  rownames_to_column(var = "sample_id") %>%
  as_tibble() %>%
  print()

d_in <- clust %>%
  left_join(expr_df) %>%
  dplyr::select(sample_id, clust, everything()) %>%
  mutate(clust = as.factor(clust)) %>%
  as.data.frame() %>%
  column_to_rownames(var = "sample_id")

d_in[1:5, 1:5]

# partition data
set.seed(818)
trainIndex <- createDataPartition(d_in$clust, p = .75, 
                                  list = FALSE, 
                                  times = 1)
head(trainIndex)

d_train <- d_in[ trainIndex,]
d_test  <- d_in[-trainIndex,]


str(d_train)
str(d_test)
```


```{r eval = FALSE}
# set seed
set.seed(818)

# set parameters for 10-fold CV, repeated 3 times
fitControl <- trainControl(method = "repeatedcv",
                           number = 10,
                           repeats = 3,
                           verboseIter = TRUE,
                           )

# train model
knn_fit <- train(clust ~ ., 
            data = d_train,
            method = "knn", 
            trControl = fitControl,
            preprocess = c("center", "scale"),
            tunelength = 10)

prediction <- predict(knn_fit, d_test)
xtab <- table(d_test$clust, prediction)
xtab
```

Caret review: 
http://www.rebeccabarter.com/blog/2017-11-17-caret_tutorial/
