---
title: "sparse_clustering"
author: "mleukam"
date: "2019-07-20"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Setup

```{r}
# Clear the workspace
rm(list = ls())
```


```{r}
knitr::opts_chunk$set(eval = FALSE)
```


```{r}
# store base R plotting parameters at startup for later reset
.pardefault <- par(no.readonly = T)

# set seed
set.seed(818)
```

Load packages
```{r}
library("tidyverse")
library("sparcl")
library("Biobase")
library("factoextra")
library("FactoMineR")
library("viridis")
library("ggdark")
library("jcolors")
library("M3C")
library("caTools")
library("ggConvexHull")
library("ggsci")
library("ggpubr")
library("viridis")
library("Rtsne")
```

note: after using ggdark, need to restore defaults of fill/color with: 
"invert_geom_defaults()"

Read in combined expression set (for pheno data)
```{r}
combined_es <- readRDS("output/combined_expressionset.rds")

```

Select gene sets from initial library
```{r}
gset_ids_complete_4 <- readRDS("output/gset_ids_complete_4.rds")
gset_ids_complete_4

names.initial <- names(gset_ids_complete_4) %>%
  enframe() %>%
  dplyr::select(gs_name = value) %>%
  print()

# remove B-cell related gene set names and gene sets used for descriptions of clusters only
# review using View function
# review unpublished uchi_t_inflamed_gs
remove.names <- c("cyt_gs", "dhit_gs", "imsig_bcells_gs", "thor_bcell_mg_igj", "thor_bcell_receptors_score", "thor_b_cell_pca_16704732", "thor_bcell_21978456", 	"thor_gp2_immune_bcell_score", "uchi_t_inflamed_gs")

names.handfiltered <- names.initial %>%
  dplyr::filter(!gs_name %in% remove.names) %>%
  pull(gs_name)
head(names.handfiltered)

gene_sets_1 <- enframe(gset_ids_complete_4) %>%
  dplyr::rename(gs_name_1 = name, genes_1 = value) %>%
  print()

gene_sets_2 <- enframe(gset_ids_complete_4) %>%
  dplyr::rename(gs_name_2 = name, genes_2 = value)

# make a table of pairwise comparisons for gene set names
comb <- combs(names.handfiltered, 2) %>%
  as.data.frame() %>%
  as_tibble() %>%
  dplyr::rename(gs_name_1 = V1, gs_name_2 = V2) %>%
  left_join(gene_sets_1, by = "gs_name_1") %>%
  left_join(gene_sets_2, by = "gs_name_2") %>%
      print()

# define function to find overlap of gene set names
overlappy <- function(genes_1, genes_2){
  prct <- (2 * length(intersect(genes_1, genes_2))) / (length(genes_1) + length(genes_2))
  prct
}

comb_prct <- comb %>% 
  mutate(prct = map2_dbl(genes_1, genes_2, overlappy)) %>%
  arrange(desc(prct)) %>%
  print(n = 100)
hist(comb_prct$prct)

# get a list of gene sets to cut
# will cut gene sets with 2/3 genes shared or more
# 17 gene sets meet the criteria
# since column choice randomly selected, will cut column two
gs_cut <- comb_prct %>%
  dplyr::filter(prct > 0.666) %>%
  pull(gs_name_2) %>%
  print()

names.lessoverlap <- names.handfiltered %>%
  enframe() %>%
  dplyr::select(gs_name = value) %>%
  dplyr::filter(!gs_name %in% gs_cut) %>%
  pull(gs_name)
print(names.lessoverlap)
length(names.lessoverlap)
# n = 121

filt_gs <- enframe(gset_ids_complete_4) %>%
  dplyr::rename(gs_name = name, genes = value) %>%
  dplyr::filter(gs_name %in% names.lessoverlap) %>%
  print()
filt_gs_list <- as.list(filt_gs$genes)
names(filt_gs_list) <- as.character(filt_gs$gs_name)
head(filt_gs_list)
  
raw_score_matrix <- readRDS("output/dlbcl_total_immune_gset_v4_results.rds") %>%
  as.data.frame() %>%
  rownames_to_column(var = "gs_names")
raw_score_matrix[1:5, 1:5]
dim(raw_score_matrix)

score_matrix <- raw_score_matrix %>%
  as_tibble() %>%
  dplyr::filter(gs_names %in% names.lessoverlap) %>%
  as.data.frame() %>%
  column_to_rownames(var = "gs_names") %>%
  t()
score_matrix[1:5, 1:5]
dim(score_matrix)
  
```

Get total number of genes
```{r}
# get a table of final genes in each gene set by filtered gene set name
filt_genes <- enframe(gset_ids_complete_4) %>%
  dplyr::rename(gs_name = name, genes = value) %>%
  dplyr::filter(gs_name %in% names.handfiltered) %>%
  dplyr::filter(!gs_name %in% gs_cut) %>%
  print()

# vector of all genes
genes <- filt_genes %>%
  pull(genes) %>%
  as_vector()

# get number of unique genes
genes %>%
  unique() %>%
  length()

# frequency table
freq_tab <- filt_genes %>%
  unnest() %>%
  group_by(genes) %>%
  count(genes) %>%
  arrange(desc(n)) %>%
  mutate(prop = n / 121) %>%
  print()

# mean frequency
freq_tab %>% pull(n) %>% as.numeric() %>% mean()

# get hugo symbols for genes
# read in conversion table for gene IDs
gencode_gtf <- read_tsv("data/gencode.v22.primary_assembly.annotation.gtf.geneinfo") %>%
  print()
freq_tab_hugo <- freq_tab %>%
  dplyr::rename(gene_id = genes) %>%
  left_join(gencode_gtf) %>%
  dplyr::select(gene_name, n, prop, gene_id) %>%
  print()
```


# Hierarchical sparse clustering: https://rdrr.io/cran/sparcl/man/HierarchicalSparseCluster.html

Manipulating an hclust object
https://stat.ethz.ch/R-manual/R-patched/library/stats/html/hclust.html

```{r}
set.seed(818)

# cases in rows and variables in columns
score_matrix[1:5, 1:5]
dim(score_matrix)

# Do tuning parameter selection for sparse hierarchical clustering
perm.out <- HierarchicalSparseCluster.permute(score_matrix, 
                                              wbounds = c(1.5,2:6), 
                                              nperms = 5)
print(perm.out)
plot(perm.out)
str(perm.out)

# Perform sparse hierarchical clustering
sparsehc <- HierarchicalSparseCluster(dists = perm.out$dists, 
                                      wbound = perm.out$bestw, 
                                      method = "complete")
par(mfrow = c(1, 2))
plot(sparsehc)
sparsehc
str(sparsehc)

# Get cluster assignments
memb <- cutree(sparsehc$hc, k = 4)
summary(as.factor(memb))
memb_df <- enframe(memb) %>%
  select(sp_clust = value) %>%
  print()

# Add cluster assignments to phenoData
pheno_data <- pData(combined_es) %>% 
  rownames_to_column(var = "sample_id") %>%
  as_tibble() %>%
  bind_cols(memb_df) %>%
  dplyr::select(sample_id, sp_clust, everything()) %>%
  print()

# Get names of nonzero weighted gene sets
gs_coef <- sparsehc$ws %>% as_tibble() %>% dplyr::rename(Wj = V1)
retained_gene_sets <- enframe(colnames(score_matrix)) %>% 
  bind_cols(gs_coef) %>%
  dplyr::rename(gs = value, index = name) %>%
  filter(Wj != 0) %>%
  arrange(desc(Wj)) %>%
  print(n = nrow(.))
```

```{r eval=FALSE}
# reset plot parameters
par(.pardefault)

# plot dendogram
fviz_dend(sparsehc$hc, 
          k = 4,
          palette = "nejm",
          show_labels = FALSE, 
          main = "Sparse Hierarchical Cluster Assignments, k = 4",
          rect = TRUE,
          rect_lty = 2,
          rect_fill = FALSE,
          lower_rect = -0.0001)
```

```{r}
# filter gene sets
# make vector of retained gene set names
keep_gs <- retained_gene_sets$gs

# use vector to filter gene sets
score_mat_filt <- score_matrix %>% 
  as.data.frame() %>%
  rownames_to_column(var = "sample_id") %>%
  as_tibble() %>%
  dplyr::select(sample_id, one_of(keep_gs)) %>%
  # add cluster assignment
  left_join(pheno_data, by = "sample_id") %>%
  dplyr::select(sample_id, sp_clust, one_of(keep_gs)) %>%
  mutate(sp_clust = as.factor(sp_clust)) %>%
  print()

sp_pca <- PCA(score_mat_filt[3:59],
    scale.unit = TRUE,
    graph = FALSE)

fviz_pca_ind(sp_pca,
             label = "none",
             pointshape = 19,
             habillage = score_mat_filt$sp_clust,
             legend.title = "Clusters") + 
  dark_theme_gray() +
  scale_color_jcolors(palette = "pal3") +
  scale_fill_jcolors(palette = "pal3") +
  geom_convexhull(alpha = 0.3, 
                  aes(fill = score_mat_filt$sp_clust),
                  show.legend = FALSE,
                  color = "#76767666")

fviz_pca_var(sp_pca)
```

Visualization with tSNE

https://www.r-bloggers.com/playing-with-dimensions-from-clustering-pca-t-sne-to-carl-sagan/

```{r}
set.seed(818)

## create score matrix in proper format
score_data <- score_mat_filt %>% 
  as.data.frame() %>%
  column_to_rownames(var = "sample_id") %>%
  dplyr::select(-sp_clust)
score_data[1:5, 1:5]

## get tSNE model
tsne_model_1 <- Rtsne(score_data, 
     dims = 2, 
     initial_dims = 57,
     perplexity = 200,
     verbose = TRUE,
     theta = 0.2,
     pca = TRUE,
     normalize = FALSE
     )

## get the two dimensional matrix for plotting
d_tsne_1 <- as.data.frame(tsne_model_1$Y) 
rownames(d_tsne_1) <- rownames(score_data)

## add groups from sparse clustering
d_tsne_1$cluster <- score_mat_filt$sp_clust
head(d_tsne_1)

## plotting the results
ggplot(d_tsne_1, aes(x = V1, y = V2, color = cluster)) +  
  geom_point() +
  xlab("") + ylab("") +
  ggtitle("t-SNE") +
  theme_classic2() +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank()) +
  scale_color_d3() +
  geom_convexhull(aes(fill = cluster), 
                  alpha = 0.1,
                  show.legend = FALSE)


```

Visualization with UMAP
```{r}
library(umap)
sp_clust_umap <- umap(score_data)

## get the two dimensional matrix for plotting
d_umap_1 <- as.data.frame(sp_clust_umap$layout)
head(d_umap_1)

## add back individual gene set expression for exploratory plotting
d_umap_1_gs <- d_umap_1 %>%
  as.data.frame() %>%
  rownames_to_column(var = "sample_id") %>%
  as_tibble() %>%
  left_join(score_mat_filt) %>%
  print()

# plot UMAP with cluster labels
ggplot(d_umap_1_gs, aes(x = V1, 
                     y = V2,
                     color = sp_clust)) +  
  geom_point() +
  geom_convexhull(alpha = 0.1,
                  show.legend = FALSE) +
  xlab("") + ylab("") +
  ggtitle("UMAP with cluster labels") +
  theme_classic2() +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank()) +
  labs(color = "Cluster") +
  scale_color_d3()

# plot UMAP with CYT score
cyt_gs <- raw_score_matrix %>%
  as.data.frame() %>%
  column_to_rownames(var = "gs_names") %>%
  as.matrix() %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column(var = "sample_id") %>%
  dplyr::select(sample_id, cyt_gs) %>%
  as_tibble() %>%
  print()

d_umap_1_gs_cyt <- d_umap_1_gs %>%
  left_join(cyt_gs) %>%
  print()

ggplot(d_umap_1_gs_cyt, aes(x = V1, 
                     y = V2,
                     color = cyt_gs)) +  
  geom_point() +
  geom_convexhull(aes(fill = sp_clust), 
                  alpha = 0.1,
                  show.legend = FALSE) +
  xlab("") + ylab("") +
  ggtitle("UMAP and CYT GSVA score") +
  theme_classic2() +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank()) +
  labs(color = "Cluster") +
  scale_color_viridis()

## DAP12 gene set
ggplot(d_umap_1_gs_cyt, aes(x = V1, 
                     y = V2,
                     color = thor_dap12_data)) +  
  geom_point() +
  geom_convexhull(aes(fill = sp_clust), 
                  alpha = 0.1,
                  show.legend = FALSE) +
  xlab("") + ylab("") +
  ggtitle("UMAP and DAP12 score") +
  theme_classic2() +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank()) +
  labs(color = "Cluster") +
  scale_color_viridis()

## CD68 gene set
ggplot(d_umap_1_gs_cyt, aes(x = V1, 
                     y = V2,
                     color = thor_cd68)) +  
  geom_point() +
  geom_convexhull(aes(fill = sp_clust), 
                  alpha = 0.1,
                  show.legend = FALSE) +
  xlab("") + ylab("") +
  ggtitle("UMAP and CD68 score") +
  theme_classic2() +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank()) +
  labs(color = "Cluster") +
  scale_color_viridis()

## Imsig macrophages
ggplot(d_umap_1_gs_cyt, aes(x = V1, 
                     y = V2,
                     color = imsig_macrophages_gs)) +  
  geom_point() +
  geom_convexhull(aes(fill = sp_clust), 
                  alpha = 0.1,
                  show.legend = FALSE) +
  xlab("") + ylab("") +
  ggtitle("UMAP and Imsig Mac score") +
  theme_classic2() +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank()) +
  labs(color = "Cluster") +
  scale_color_viridis()

## Trem1
ggplot(d_umap_1_gs_cyt, aes(x = V1, 
                     y = V2,
                     color = thor_trem1_data)) +  
  geom_point() +
  geom_convexhull(aes(fill = sp_clust), 
                  alpha = 0.1,
                  show.legend = FALSE) +
  xlab("") + ylab("") +
  ggtitle("UMAP and Trem1 GSVA score") +
  theme_classic2() +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank()) +
  labs(color = "Cluster") +
  scale_color_viridis()
```
